### ISSUE TITLE
Verificar erro 500 no azure

### ISSUE THREAD

**Issue by agcjunior** [dunebuddy/skepsi#20]
Ao tentar acessar a api com a seguinte url: http://skepsiteste.azurewebsites.net/api/pensamentos
recebo um Internal Server Erro.

**Comment by dunebuddy** [comment]
Ok, já sei qual o problema, o Azure não suporta LocalDB, vamos ter de migrar o projeto para SqlServer CE, eu faço ou você faz @agcjunior?

**Comment by pisandelli** [comment]
impacto no meu trabalho?

Em 28 de julho de 2015 15:50, Paulo Junior notifications@github.com
escreveu:

**Comment by agcjunior** [comment]
Sim Pisa, o Paulo ficou de ajustar isso. Não dá pra chamar o método da Api.
