### ISSUE TITLE
Parâmetro para incluir pensamento

### ISSUE THREAD

**Issue by pisandelli** [dunebuddy/skepsi#38]
Onde devo incluir o pensamento?
Tentei e sempre dá "Bad Request" 400....
Está implementado?

@agcjunior @dunebuddy

**Comment by pisandelli** [comment]
@agcjunior @dunebuddy 
Vi que no arquivo `PensamentoControlller.cs` na linha 36 temos: 

``` C#
[HttpPost]
        public IHttpActionResult Incluir([FromBody] String pensamento)
        {
            if (String.IsNullOrEmpty(pensamento))
            {
                return BadRequest("Pensamento não pode ser vazio");
            }

            Pensamento novoPensamento = new Pensamento()
            {
                CriadoEm = DateTime.Today.Date,
                DescricaoPensamento = pensamento
            };

            _context.Pensamentos.Add(novoPensamento);
            _context.SaveChanges();

            return Created<Pensamento>(Request.RequestUri + novoPensamento.Id.ToString(), novoPensamento);
        }
```

Tentei `pensamento`e até `novoPensamento` sem sucesso. Sempre retorna **_"Pensamento não pode ser vazio"_** sendo que pelo console posso ver que o objeto está sendo enviado. Tentei enviar diretamente pelo JS, sem vir do `input` e nada... mesmo resultado.

**Comment by agcjunior** [comment]
corrigido

**Comment by pisandelli** [comment]
Fiz o merge e testei. Tudo ok! :+1:

**Comment by pisandelli** [comment]
O primeiro teste foi realizado tranquilamente...
Tentei novamente agora e voltou a dar 'Bad Request' - Erro 400

**Comment by pisandelli** [comment]
Subi um fix... Deu certo.

**Comment by pisandelli** [comment]
O problema é que a solução do @agcjunior não permitia adicionar aspas no campo.
Este último Fix (32964c8) permite o uso ou não de aspas.
Preciso que vocês testem para confirmar que o Bug foi resolvido.
